name: release

on:
  workflow_call:

env:
  NPM_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # GitHub Packagesへの公開
  release:
    runs-on: ubuntu-latest
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: https://npm.pkg.github.com
          scope: '@room-601'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Create Release Pull Request or Version Packages
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: npx lerna publish from-package --yes --preid alpha --pre-dist-tag alpha --no-verify-access

  # npmjs.orgへの公開
  release-to-npm:
    needs: release
    if: needs.release.outputs.hasChangesets == 'false'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          scope: '@kosuketakahashi0410'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Pre setting for npmjs.org
        run: |
          for file in packages/*/package.json; do
            jq '.name = (.name | gsub("@room-601/";"@kosuketakahashi0410/")) | .publishConfig.access = "public"' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
          done
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/*/package.json
          git commit -m "temp: change package names for npmjs.org [skip ci]"
      
      - name: Publish
        run: npx lerna publish from-package --yes --preid alpha --pre-dist-tag alpha --no-verify-access